// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvckemylcqzekfzqjscm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Y2tlbXlsY3F6ZWtmenFqc2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3Nzc5NzcsImV4cCI6MjA2MjM1Mzk3N30.rlwghlZ0G14C8lGXmdrgxzY9toatNCPgpTgdy1UZHKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);